version: "3.9"

networks:
  todo_net:
#    driver: bridge

services:
  frontend:
    build: ./frontend
    container_name: frontend
    working_dir: /app-front
    volumes:
      - ./frontend:/app-front
    ports:
      - 3000:5173
    # env_file: ./default.env
    networks:
      - todo_net
    tty: true
    restart: always
    command: npm run dev

  backend:
    build: 
      context: ./backend
    user: node
    container_name: backend
    working_dir: /app-back
    volumes:
      - ./backend:/app-back
    depends_on:
      - db
    tty: true
    ports:
      - 3001:3001
    env_file: ./default.env
    networks:
      - todo_net
    command: npm run start
    restart: always

  
  db:
    container_name: database
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    env_file: ./default.env
    networks:
      - todo_net